import '@/styles/globals.css'
import Link from 'next/link'
import styles from '@/app/hooks/layout.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <nav>
        <Link href='/hooks' className={styles.link}>
          Hooks
        </Link>
        <Link href='/hooks/use-state' className={styles.link}>
          useState
        </Link>
        <Link href='/hooks/use-reducer' className={styles.link}>
          useReducer
        </Link>
        <Link href='/hooks/use-effect' className={styles.link}>
          useEffect
        </Link>
        <Link href='/hooks/use-layout-effect' className={styles.link}>
          useLayOutEffect
        </Link>
        <Link href='/hooks/memo' className={styles.link}>
          memo
        </Link>
      </nav>
      <div>{children}</div>
    </div>
  )
}
