import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import { CounterProvider } from '@/context/CounterProvider'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

/**
 * ページ表示時に「　| Next App」となる
 * 「%s」ページ毎に静的または動的に設定されたtitleが入る
 * もし、titleが設定されていない場合はdefaultが入る
 */
export const metadata = {
  title: {
    default: 'Create Next App',
    template: `%s | Next App`
  },
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  team,
  analytics
}: {
  children: React.ReactNode
  team: React.ReactNode
  analytics: React.ReactNode
}) {
  return (
    <html lang='ja'>
      <body className={inter.className} suppressHydrationWarning={true}>
        <CounterProvider>{children}</CounterProvider>
        {/* <div>{team}</div>
        <div>{analytics}</div> */}
      </body>
    </html>
  )
}
